- tools-javascript-formatter/.eslintrc
Airbnb uses [eslint default brace-syles rule](http://eslint.org/docs/rules/brace-style) which looks much better.
> Reverting brace-style rule to default

- tools-javascript-formatter/.eslintrc
jsx props indentation was required to use 2 space, corrected to use tabs instead
> correct ident check rules on jsx props

- tools-javascript-formatter/.eslintrc
the rule import/no-extraneous-dependencies do not know where is the test file.
This change remove the complains about using devDependency in a test file
> fix(javascript-formatter/eslint): add missing rules configuration

- tools-javascript-formatter/.eslintrc
no-tabs rules where added to airbnb eslint rules wich we depend on,
this change disable said rules
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/CHANGELOG.md#600--2016-09-06
> fix: disable no-tabs rules

- tools-root-github/.gitignore
Ignore Talend web apps build directory by default
> fix(github-root): Ignore default build directory

- tools-javascript/.eslintrc
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?**
**What is the current behavior?** (You can also link to an open issue here)
The wildcard to specify tests files for import/no-extraneous-dependencies is not correct.
A lint would throw an error on tests files, on imports from dev dependencies.
**What is the new behavior?**
Fix the rule, like specified [here](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md)
**Does this PR introduce a breaking change?**
If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
**Other information**:
@Talend/frontend don't forget to change the .eslintrc file in your projects
> fix(eslint): import/no-extraneous-dependencies

- tools-javascript/.eslintrc
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?**
**What is the current behavior?** (You can also link to an open issue here)
The linter throw an error on `Shape` propType usage check, even when it is unable to check that.
ex: 
```javascript
function MyComponent(props) {
return props.actions.map((action) => <div>{action.label}</div>)
}
MyComponent.propTypes = {
actions: React.PropTypes.arrayOf(
React.PropTypes.shape({
label: React.PropTypes.string,
})
),
}
```
An error will be thrown on actions.**.label because the linter cannot check properly that label is used.
**What is the new behavior?**
*This is a proposal*
There won't be any check on `shape` propType.
**Does this PR introduce a breaking change?**
If this PR contains a breaking …
> style(eslint): skip Shape propType check

- tools-javascript/compilation/react/.babelrc
Introduces by https://github.com/Talend/react-talend-components/pull/57
> fix: Internet Explorer does not support Object.assign method

- tools-root-github/.github/PULL_REQUEST_TEMPLATE.md
- tools-root-github/CONTRIBUTING.md
* Removes pull request type section. That information is redundant of the
pull request title. Adds deletion notice.
* Removes pull request requirements checkboxes. Those should only be
used to mark remaining tasks/todos on a given pull request.
* Removes pull request breaking change checkboxes. Now asks for the
section to be removed if the pull request doesn't contain any breaking change.
> chore(github): Updates pull request template

- tools-root-github/.github/PULL_REQUEST_TEMPLATE.md
We want to modify the current .github/PULL_REQUEST_TEMPLATE.md to reflect what we decided during the tab meeting of 03.05.17. 
See proposal: https://wiki.talend.com/display/rd/Pull+Requests
> Modify PR template according to TAB 03.05.17

- tools-root-github/.github/PULL_REQUEST_TEMPLATE.md
At the moment the PR template shows the original link to the PR template. However, it's not needed, and it should be made invisible. 
In addition, add a small statement about the fact that additional checkboxes can be added.
> Add comments for non-mandatory information

- tools-javascript/.eslintrc
As discussed with @jmfrancois, this rule is not used and cause many useless errors.
> chores(eslint): no more forbidden proptypes

- tools-java-formatter/README.md
changed the documentation for the java formatter in order to use a release version of the formatter maven plugin instead of a SNAPSHOT one.
> doc(java): changed maven formatter plugin to fixed version

- tools-root-github/CONTRIBUTING.md
**What is the problem this Pull Request is trying to solve?**
On projects with Jenkins CI on it, there are tools used by devops that are not compatible with `@` in branch name.
**What is the chosen solution to this problem?**
Add a note to forbid this char.
> fix(contributing): forbid @ in branch name

- tools-java-formatter/README.md
nothing was specified on the .properties file encoding but IntelliJ uses the default platform encoding where java `java.util.PropertyResourceBundle` uses ISO-8859-1 by default.
So I suggest IntelliJ and Eclipse are configured with *ISO-8859-1* encoding for .properties files. (Eclipse does it be default but I added the procedure for consistency)
> doc(java):added .properties file encoding in java readme

- tools-java-formatter/README.md
**What is the problem this Pull Request is trying to solve?**
Intellij and eclipse had 2 different ways of defining the java import order and also have different definitions.
**What is the chosen solution to this problem?**
have one single source for the import order definition, the IntelliJ Eclipse formatter plugin is also compatible with the eclipse file *.importorder* . Also specify the eclipse procedure to set this up.
> doc(java): update the import order setup

- tools-java-formatter/README.md
This is because the code formatter plugin automatically choose lineEnding characters according to the operation system. On windows, it will be CRLF, which is different from the linux/macos. If we do a -Dformat on windows, it will mark every lines of all the text files as modified.
By forcing the lineEnding property to LF, it will convert all CRLF to LF during the formatting step and save it to the files. This behavior is consistent with the suggested core.autocrlf setting for projects with developpers accross different platforms.
> Add lineEnding property to code formatter setting

- tools-javascript/.eslintrc
ESlint did not match Prettier config regarding arrow-parens
Align ESlint config regarding arrow-parens to fit Prettier one
* https://eslint.org/docs/rules/arrow-parens
* https://eslint.org/docs/rules/no-mixed-operators
> chore(eslint): align lint with prettier rules

- talend-tools-maven-plugin/pom.xml
- talend-tools-maven-plugin/src/main/java/org/talend/tools/blackduck/HubDetectMojo.java
Overall goal is to exclude test/temporary folders hub-detect abusively scans (things we don't deliver).
Also it contains a few default fixes like log level can't be ALL with maven slf4j or the default scope should be runtime which includes compile but not only.
> fix hub-detect defaults + adding exclusions to HubDetectMojo

- tools-root-maven/pom.xml
better defaults and built-in in the config exclusion support
note: before merging we need to ensure it is synch-ed on central (http://repo1.maven.org/maven2/org/talend/tools/talend-tools-maven-plugin/maven-metadata.xml include latest=1.0.2)
> upgrading talend-tools-maven-plugin

- tools-scss-formatting/.sass-lint.yml
`sass-lint` waits for hex colors in uppercase while `prettier` will change them into lowercase.
To avoid a lot of errors, since Prettier will reformat only change files, I propose to desactivate those errors from that tool
> chore: Prettier deals with hex-notation rule

- tools-javascript/compilation/react/.babelrc
**What is the problem this PR is trying to solve?**
Current babelrc use babel-preset-es2015 which is kind of deprecated.
**What is the chosen solution to this problem?**
Set configuration for babel-preset-env
> chore: update babelrc to use preset-env

- tools-k8s-connect/README.md
- tools-k8s-connect/k8s-cluster-connect.bashrc
- tools-k8s-connect/k8s-cluster-connect.sh
Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-b] region 
Helper script to connect to Talend K8S clusters.
region : value should be in dev, int, int-admin, qa-admin, ci-admin, at, at-admin, staging, staging-admin, us, eu, ap, us-admin, eu-admin, ap-admin, az-sandbox, az-sandbox-admin, az-staging, az-staging-admin,az-prodanz, az-prodanz-admin, az-produs, az-produs-admin
Available options:
-h, --help      Print this help and exit
-v, --verbose   Print script debug info
-b, --bashrc   Display an example of lines to add in your bashrc file to ease kubernetes usage
> feat(k8s-connect): Adding scripts to ease connection to K8S

- tools-java-formatter/src/main/resources/talend_java_eclipse_formatter.xml
The Eclipse formatter currently wraps lines automatically which makes the code harder to read in common use-cases like the use of builders.
Ex:
```java
Record.builder()
.withType(RECORD)
.withEntry(entry1)
.withEntry(entry2)
.build()
```
Becomes:
```java
Record.builder().withType(RECORD).withEntry(entry1).withEntry(entry2).build()
```
This is worked around in a lot of places by adding an empty comment at the end of lines that should not be wrapped, ex:
```java
Record.builder() //
.withType(RECORD) //
.withEntry(entry1) //
.withEntry(entry2) //
.build()
```
This shows that it's time for the rule to evolve.
This change makes the formatter preserve wrapping, one is free to remove them manually where necessary.
> Improve Eclipse Java formatter, stop wrapping lines
