Talend/tools

- tools-scss-formatting/.sass-lint.yml
- tools-scss-formatting/README.md
* Adds comprehensive README containing the editor's lint plugin installation instructions
* Adds .sass-lint.yml containing all the SCSS linting rules
> chore: Adds SCSS formatting tools

- tools-javascript-formatter/.editorconfig
apply the tab indentation to js, jsx, css, scss files,
apply 2 space indent for json files
> update editor config to take into account tab indent

- LICENSE
- README.md
* Adds basic Readme file
* Adds Apache 2 license file
Fixes #7
> Adds Readme and License

- tools-javascript-compilation/angular/.babelrc
- tools-javascript-compilation/react/.babelrc
#12 
* one for angular including es2015 and rest spread operator support
* one for react including es2015, react, rest spread operation and class property support
> feat: added two babelrc

- tools-root-github/.github/PULL_REQUEST_TEMPLATE.md
- tools-root-github/.gitignore
- tools-root-github/CONTRIBUTING.md
This works contains:
* a pull request template model
* a contributing guidelines that the project should follow
* a shared .gitignore file
> feat(github-root): add common files for a github project

- tools-scss-formatting/.sass-lint.yml
Change default path in order to reach more common configurations
> chore(sass-lint): Change default path

- tools-javascript/.eslintrc
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?**
**What is the current behavior?** (You can also link to an open issue here)
Strings in eslintrc JSON were surrounded by single quotes that is not allowed in JSON
**What is the new behavior?**
Replaced them by double quotes
**Does this PR introduce a breaking change?**
If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
**Other information**:
> fix(javascript/eslintrc): JSON string with double-quotes

- tools-javascript/.eslintrc
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?**
**What is the current behavior?** (You can also link to an open issue here)
Default behavior is .jsx extension
**What is the new behavior?**
Force it to be .js
**Does this PR introduce a breaking change?**
If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
**Other information**:
> style(eslint): add jsx file extension rule

- tools-scss-formatting/.sass-lint.yml
> fix(sass-lint): Change indentation rule

- tools-root-github/.github/PULL_REQUEST_TEMPLATE.md
* Add code coverage check
* Add new technical issue check
> doc : update PR template

- tools-java-formatter/README.md
- tools-java-formatter/pom.xml
> DEVOPS-1729 Nexus migration: Update URLs [master]

- tools-root-github/CONTRIBUTING.md
We would like to change the Contributing.md file according to what has been discussed during the TAB meeting held on 03.05.17.
> Modify Contributing.md according to TAB 03.05.17

- tools-root-github/.github/PULL_REQUEST_TEMPLATE.md
* Removes Acronyms
* Removes extra newlines at end of file
> Pull request template cleanup

- tools-java-formatter/src/main/resources/codetemplates.xml
Change static value for year in license to variable
> chore: fix year in file comment template

- tools-javascript/README.md
**What is the problem this Pull Request is trying to solve?**
JS formatter on webstorm doesn't precise eslint or prettier.
**What is the chosen solution to this problem?**
Update js formatter procedure on webstorm.
> doc(javascript): webstorm js formatter using eslint/prettier

- tools-java-formatter/pom.xml
- tools-java-formatter/src/main/resources/talend_java_eclipse_formatter.xml
Feedback after using company-wide formatting rules in Talend PlatformServices.
Changes to java code formatting rules :
1. set max-line length to 120
2. lines are always wrapped
In order to be able to use checkstyle LineLength
3. wrap qualified invocations, one per line for good looking DSL
calls.
We use checkstyle LineLength.
Checkstyle can check for a fixed size maximum line length.
So line-wrapping is always done now.
Before change :
``` java
@Component
public class UserConverter implements Converter<User, UserTO> {
public User toScim(UserTO userTO, List<GroupTO> groupTOs) {
// Building user now...
User user = new User.Builder(userTO.getUsername()).setId(userScimId).setExternalId(userTO.getKey().toString())
.setName(name).setDisplayName(displayName).setNickName(nickName).setProfileUrl(pr …
```
> TPSVC : java format line-wrapping always, pretty DSL

- talend-tools-maven-plugin/pom.xml
- talend-tools-maven-plugin/src/main/java/org/talend/tools/blackduck/BlackduckBase.java
- talend-tools-maven-plugin/src/main/java/org/talend/tools/blackduck/BlackduckValidateMojo.java
- talend-tools-maven-plugin/src/main/java/org/talend/tools/blackduck/HubDetectMojo.java
Simple way to prevent a release if too much violations (HIGH for release and components ATM) are encountered
> simple blackduck plugin to validate high violations in a build

- tools-javascript/.prettier.rc
It's hard to build a prettier rc conf sync with eslint;
let's propose to put a prettier rc here
> chore(javascript): add prettier rc

- tools-root-github/CONTRIBUTING.md
The branch names that we use are reasonable, but don't correspond to the spec in this guideline.
Updated branch names to those in common use.
> chore: Update branch names to common usage.

- tools-java-formatter/pom.xml
the formater template has been updated and this PR bump the artifact version in order to release it.
> feat(java): update formater pom for next release

- tools-k8s-connect/k8s-cluster-connect.sh
Add AU region for k8s login script.
> chore(UNTRACKED/k8s): add AU region to k8s connect tool.
